services:
  - type: web
    name: bajaj-fastapi
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT --workers=1
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        sync: false
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: "production"
