branch-defaults:
  main:
    environment: bajaj-api-prod
    group_suffix: null
environment-defaults:
  bajaj-api-prod:
    branch: null
    repository: null
global:
  application_name: bajaj-api
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.10 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application